# Dockerfile for Flask Backend
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the Flask project
COPY WAI_API /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port
EXPOSE 5000

# Start the Flask application

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
#Needs be startet with doccker run -p 5000:5000 <image-name>
