name: Run Tests (Python)

on:
  push:
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3 
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          cd WAI_API
          python -m pip install --upgrade pip  # Upgrade pip (optional)
          pip install -r requirements.txt  # Replace with your requirements file path
      - name: Run tests
        run: |
          cd WAI_API
          python test_app.py  # Adjust the command if your test script has arguments
