name: Run Lighthouse Report

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull stupe562/docker.vaadin:latest

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name my-app-container stupe562/docker.vaadin:latest

    - name: Wait for the container to be ready
      run: |
        until curl -s http://localhost:8080; do
          echo "Waiting for the container to be ready..."
          sleep 5
        done

    - name: Install Lighthouse CLI
      run: npm install -g lighthouse

    - name: Run Lighthouse
      run: |
        lighthouse http://localhost:8080 --chrome-flags="--headless --no-sandbox --ignore-certificate-errors --disable-gpu" --output html --output-path ./lighthouse-report.html
    
    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-report
        path: ./lighthouse-report.html

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and Push Lighthouse Report to gh-pages
      run: |
        git checkout --orphan gh-pages
        git add -f ./lighthouse-report.html
        git commit -m "Add Lighthouse report"
        git push -f origin gh-pages

    - name: Stop and remove Docker container
      run: |
        docker stop my-app-container
        docker rm my-app-container


    - name: Stop and remove Docker container
      run: |
        docker stop my-app-container
        docker rm my-app-container