name: Lighthouse

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Lighthouse
      run: npm install -g lighthouse

    - name: Run Lighthouse
      run: lighthouse http://localhost:8080 --output json --output-path ./lighthouse-results.json --chrome-flags="--headless --no-sandbox --disable-gpu"

    - name: Upload Lighthouse Results
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-results
        path: ./lighthouse-results.json
