name: Locust Load Testing on Docker Image

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  locust:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull stupe562/docker.flask:latest

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name test-container stupe562/docker.flask:latest

      - name: Wait for the container to be ready
        run: sleep 15

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Run Locust load tests
        run: |
          locust -f locust.py --headless -u 10 -r 1 --run-time 1m --host=http://localhost

      - name: Stop Docker Container
        run: docker stop test-container

      - name: Remove Docker Container
        run: docker rm test-container
